"""Built-in themes, icons, social presets, and starter templates."""

THEME_PRESETS = {
    "Dark Blue": {
        "background": "#151922",
        "panel": "#1f2633",
        "sidebar": "#111823",
        "accent": "#4f8cff",
        "hover": "#29384f",
        "active": "#315fbd",
        "border": "#344052",
        "text": "#f4f7fb",
        "muted_text": "#98a3b7",
        "rounding": 8,
        "padding": 14,
        "item_spacing": 10,
        "font_scale": 1.0,
        "border_thickness": 1,
        "shadow": "soft",
    },
    "Cyber Purple": {
        "background": "#17131f",
        "panel": "#241b34",
        "sidebar": "#130f1d",
        "accent": "#b26cff",
        "hover": "#39284f",
        "active": "#7c3fdb",
        "border": "#47395d",
        "text": "#fbf7ff",
        "muted_text": "#b5a5c8",
        "rounding": 10,
        "padding": 14,
        "item_spacing": 11,
        "font_scale": 1.0,
        "border_thickness": 1,
        "shadow": "glow",
    },
    "Emerald Green": {
        "background": "#111c18",
        "panel": "#1a2924",
        "sidebar": "#0e1715",
        "accent": "#28c487",
        "hover": "#203d35",
        "active": "#1d8e65",
        "border": "#2d4a40",
        "text": "#f0fff8",
        "muted_text": "#92b5a7",
        "rounding": 8,
        "padding": 14,
        "item_spacing": 10,
        "font_scale": 1.0,
        "border_thickness": 1,
        "shadow": "soft",
    },
    "Red/Black": {
        "background": "#130f10",
        "panel": "#201819",
        "sidebar": "#0c0a0a",
        "accent": "#ef4444",
        "hover": "#3b2426",
        "active": "#b52b31",
        "border": "#493034",
        "text": "#fff5f5",
        "muted_text": "#bca0a0",
        "rounding": 7,
        "padding": 13,
        "item_spacing": 10,
        "font_scale": 1.0,
        "border_thickness": 1,
        "shadow": "soft",
    },
    "Minimal Dark": {
        "background": "#171717",
        "panel": "#242424",
        "sidebar": "#101010",
        "accent": "#d8d8d8",
        "hover": "#303030",
        "active": "#3c3c3c",
        "border": "#3a3a3a",
        "text": "#f5f5f5",
        "muted_text": "#a0a0a0",
        "rounding": 5,
        "padding": 12,
        "item_spacing": 9,
        "font_scale": 1.0,
        "border_thickness": 1,
        "shadow": "none",
    },
    "Glassmorphism": {
        "background": "#18202a",
        "panel": "#263443",
        "sidebar": "#1d2935",
        "accent": "#7dd3fc",
        "hover": "#344a5e",
        "active": "#246a86",
        "border": "#6b879a",
        "text": "#f8fbff",
        "muted_text": "#b8c8d7",
        "rounding": 12,
        "padding": 16,
        "item_spacing": 12,
        "font_scale": 1.0,
        "border_thickness": 1,
        "shadow": "glass",
    },
    "Light Professional": {
        "background": "#eef2f7",
        "panel": "#ffffff",
        "sidebar": "#dde6f2",
        "accent": "#2563eb",
        "hover": "#d9e7ff",
        "active": "#bfdbfe",
        "border": "#c7d2e3",
        "text": "#172033",
        "muted_text": "#64748b",
        "rounding": 8,
        "padding": 14,
        "item_spacing": 10,
        "font_scale": 1.0,
        "border_thickness": 1,
        "shadow": "soft",
    },
}


ICON_PRESETS = ["", "[H]", "[*]", "[S]", "[C]", "[G]", "[W]", "[D]", "[GH]", "[YT]", "[X]", "[IG]", "[WEB]"]

SOCIAL_PLATFORMS = {
    "Discord": {"icon": "[D]", "url": "https://discord.com/"},
    "YouTube": {"icon": "[YT]", "url": "https://youtube.com/"},
    "TikTok": {"icon": "[TT]", "url": "https://tiktok.com/"},
    "GitHub": {"icon": "[GH]", "url": "https://github.com/"},
    "Website": {"icon": "[WEB]", "url": "https://example.com/"},
    "Twitter/X": {"icon": "[X]", "url": "https://x.com/"},
    "Instagram": {"icon": "[IG]", "url": "https://instagram.com/"},
    "Custom Link": {"icon": "[LINK]", "url": "https://example.com/"},
}


TEMPLATE_LIBRARY = {
    "Software Launcher Menu": {
        "project_name": "Software Launcher",
        "menu_title": "Launcher",
        "nav_position": "left",
        "nav_style": "vertical sidebar",
        "theme": "Dark Blue",
        "categories": [
            {
                "name": "Home",
                "icon": "[H]",
                "components": [
                    {"type": "header_text", "label": "Welcome"},
                    {"type": "text_label", "label": "Choose a tool or workflow to launch."},
                    {"type": "feature_card", "props": {"title": "Main Tool", "description": "Start the primary workspace.", "button_text": "Launch"}},
                    {"type": "status_badge", "label": "Ready", "props": {"status": "Ready", "badge_color": "#28c487"}},
                ],
            },
            {
                "name": "Tools",
                "icon": "[*]",
                "components": [
                    {"type": "button", "label": "Open Editor"},
                    {"type": "button", "label": "Open Viewer"},
                    {"type": "checkbox", "label": "Start minimized"},
                ],
            },
            {
                "name": "Settings",
                "icon": "[S]",
                "components": [
                    {"type": "combo_box", "label": "Startup Profile", "props": {"options": ["Default", "Work", "Presentation"], "default_index": 0}},
                    {"type": "slider_int", "label": "Recent Items", "props": {"min": 1, "max": 20, "default_value": 8}},
                    {"type": "input_text", "label": "Workspace Name"},
                ],
            },
        ],
    },
    "Admin Dashboard": {
        "project_name": "Admin Dashboard",
        "menu_title": "Admin Console",
        "nav_position": "left",
        "nav_style": "icon sidebar",
        "theme": "Light Professional",
        "categories": [
            {"name": "Overview", "icon": "[H]", "components": [{"type": "header_text", "label": "Overview"}, {"type": "status_badge", "label": "Systems Online"}, {"type": "feature_card", "props": {"title": "Reports", "description": "Review recent activity summaries.", "button_text": "View"}}]},
            {"name": "Users", "icon": "[U]", "components": [{"type": "input_text", "label": "Search Users"}, {"type": "button", "label": "Invite User"}, {"type": "checkbox", "label": "Require Approval"}]},
            {"name": "Audit", "icon": "[A]", "components": [{"type": "combo_box", "label": "Log Filter", "props": {"options": ["All", "Warnings", "Errors"], "default_index": 0}}, {"type": "button", "label": "Export Audit Log"}]},
        ],
    },
    "Settings Panel": {
        "project_name": "Settings Panel",
        "menu_title": "Settings",
        "nav_position": "top",
        "nav_style": "top tabs",
        "theme": "Minimal Dark",
        "categories": [
            {"name": "General", "icon": "[G]", "components": [{"type": "checkbox", "label": "Launch on startup"}, {"type": "combo_box", "label": "Language", "props": {"options": ["English", "Spanish", "German", "Japanese"]}}, {"type": "slider_float", "label": "Interface Scale", "props": {"min": 0.8, "max": 1.4, "default_value": 1.0, "format": "%.1f"}}]},
            {"name": "Appearance", "icon": "[A]", "components": [{"type": "color_picker", "label": "Accent Color"}, {"type": "slider_int", "label": "Rounding", "props": {"min": 0, "max": 16, "default_value": 8}}, {"type": "checkbox", "label": "Compact Mode"}]},
        ],
    },
    "Game Settings Menu": {
        "project_name": "Game Settings",
        "menu_title": "Game Settings",
        "nav_position": "left",
        "nav_style": "vertical sidebar",
        "theme": "Emerald Green",
        "categories": [
            {"name": "Graphics", "icon": "[G]", "components": [{"type": "combo_box", "label": "Quality", "props": {"options": ["Low", "Medium", "High", "Ultra"], "default_index": 2}}, {"type": "checkbox", "label": "VSync"}, {"type": "slider_float", "label": "Brightness", "props": {"min": 0.0, "max": 1.0, "default_value": 0.65}}]},
            {"name": "Audio", "icon": "[A]", "components": [{"type": "slider_int", "label": "Master Volume"}, {"type": "slider_int", "label": "Music Volume"}, {"type": "checkbox", "label": "Mute In Background"}]},
            {"name": "Controls", "icon": "[C]", "components": [{"type": "keybind", "label": "Interact"}, {"type": "keybind", "label": "Open Map"}, {"type": "slider_float", "label": "Mouse Sensitivity", "props": {"min": 0.1, "max": 5.0, "default_value": 1.0}}]},
        ],
    },
    "Social Hub": {
        "project_name": "Social Hub",
        "menu_title": "Social Links",
        "nav_position": "top",
        "nav_style": "pill tabs",
        "theme": "Cyber Purple",
        "categories": [
            {"name": "Links", "icon": "[WEB]", "components": [{"type": "header_text", "label": "Find Us Online"}, {"type": "social_link", "label": "Discord", "props": {"platform": "Discord", "url": "https://discord.com/", "icon": "[D]"}}, {"type": "social_link", "label": "GitHub", "props": {"platform": "GitHub", "url": "https://github.com/", "icon": "[GH]"}}, {"type": "social_link", "label": "Website", "props": {"platform": "Website", "url": "https://example.com/", "icon": "[WEB]"}}]},
            {"name": "Updates", "icon": "[U]", "components": [{"type": "status_badge", "label": "Online"}, {"type": "footer_text", "label": "Version 1.0.0"}]},
        ],
    },
    "Config Manager": {
        "project_name": "Config Manager",
        "menu_title": "Config Manager",
        "nav_position": "left",
        "nav_style": "vertical sidebar",
        "theme": "Dark Blue",
        "categories": [
            {"name": "Profiles", "icon": "[C]", "components": [{"type": "combo_box", "label": "Active Config", "props": {"options": ["Default", "Workstation", "Laptop"]}}, {"type": "button", "label": "Load Config"}, {"type": "button", "label": "Save Config"}]},
            {"name": "Import", "icon": "[I]", "components": [{"type": "input_text", "label": "Config Path"}, {"type": "button", "label": "Import File"}, {"type": "checkbox", "label": "Validate before import"}]},
        ],
    },
    "Minimal ImGui Menu": {
        "project_name": "Minimal Menu",
        "menu_title": "ImGui Menu",
        "nav_position": "left",
        "nav_style": "vertical sidebar",
        "theme": "Minimal Dark",
        "categories": [
            {"name": "Main", "icon": "[H]", "components": [{"type": "header_text", "label": "Main"}, {"type": "checkbox", "label": "Enable Feature"}, {"type": "slider_float", "label": "Amount"}, {"type": "button", "label": "Apply"}]},
            {"name": "Config", "icon": "[C]", "components": [{"type": "combo_box", "label": "Preset"}, {"type": "button", "label": "Save"}, {"type": "button", "label": "Reset"}]},
        ],
    },
    "Premium Sidebar Menu": {
        "project_name": "Premium Sidebar",
        "menu_title": "Control Center",
        "nav_position": "left",
        "nav_style": "vertical sidebar",
        "theme": "Glassmorphism",
        "categories": [
            {"name": "Dashboard", "icon": "[D]", "components": [{"type": "header_text", "label": "Control Center"}, {"type": "feature_card", "props": {"title": "Quick Start", "description": "Open the primary workflow.", "button_text": "Start"}}, {"type": "feature_card", "props": {"title": "Workspace", "description": "Manage local settings and tools.", "button_text": "Manage"}}]},
            {"name": "Modules", "icon": "[M]", "components": [{"type": "checkbox", "label": "Enable Module A"}, {"type": "checkbox", "label": "Enable Module B"}, {"type": "slider_int", "label": "Module Limit"}]},
            {"name": "Account", "icon": "[A]", "components": [{"type": "text_label", "label": "Local profile controls"}, {"type": "input_text", "label": "Display Name"}, {"type": "button", "label": "Update Profile"}]},
        ],
    },
}


THEME_PRESETS.update(
    {
        "Cyber Blue": {
            "background": "#07111f",
            "primary_background": "#07111f",
            "secondary_background": "#0c233d",
            "panel": "#101b2e",
            "card": "#14243a",
            "sidebar": "#081525",
            "accent": "#28a8ff",
            "accent2": "#6fffe9",
            "hover": "#17365a",
            "active": "#0e66b8",
            "nav_active": "#0e66b8",
            "nav_hover": "#17365a",
            "danger": "#ff4d6d",
            "success": "#33e6a4",
            "warning": "#ffd166",
            "border": "#234569",
            "shadow_color": "#00aaff",
            "text": "#eef9ff",
            "muted_text": "#8fb5d1",
            "rounding": 10,
            "padding": 15,
            "item_spacing": 11,
            "frame_padding": 8,
            "window_padding": 15,
            "font_scale": 1.0,
            "border_thickness": 1,
            "button_height": 36,
            "card_padding": 16,
            "glow_intensity": 0.7,
            "alpha": 0.98,
            "shadow": "glow",
        },
        "Neon Purple": {
            "background": "#130b22",
            "primary_background": "#130b22",
            "secondary_background": "#251044",
            "panel": "#201431",
            "card": "#2b1744",
            "sidebar": "#10081d",
            "accent": "#c084fc",
            "accent2": "#f472b6",
            "hover": "#3b1d5e",
            "active": "#7c3aed",
            "nav_active": "#7c3aed",
            "nav_hover": "#3b1d5e",
            "danger": "#fb7185",
            "success": "#34d399",
            "warning": "#fbbf24",
            "border": "#553278",
            "shadow_color": "#d946ef",
            "text": "#fff7ff",
            "muted_text": "#c8afd8",
            "rounding": 12,
            "padding": 15,
            "item_spacing": 12,
            "frame_padding": 8,
            "window_padding": 16,
            "font_scale": 1.0,
            "border_thickness": 1,
            "button_height": 36,
            "card_padding": 16,
            "glow_intensity": 0.75,
            "alpha": 0.98,
            "shadow": "glow",
        },
        "Emerald Matrix": {
            "background": "#06130e",
            "primary_background": "#06130e",
            "secondary_background": "#0d2a1f",
            "panel": "#10251d",
            "card": "#163328",
            "sidebar": "#071a13",
            "accent": "#22c55e",
            "accent2": "#a3e635",
            "hover": "#1d4434",
            "active": "#15803d",
            "nav_active": "#15803d",
            "nav_hover": "#1d4434",
            "danger": "#ef4444",
            "success": "#34d399",
            "warning": "#eab308",
            "border": "#285b45",
            "shadow_color": "#22c55e",
            "text": "#effff6",
            "muted_text": "#90bba5",
            "rounding": 8,
            "padding": 14,
            "item_spacing": 10,
            "frame_padding": 8,
            "window_padding": 14,
            "font_scale": 1.0,
            "border_thickness": 1,
            "button_height": 34,
            "card_padding": 15,
            "glow_intensity": 0.65,
            "alpha": 0.98,
            "shadow": "soft",
        },
        "Redline Dark": {
            "background": "#12090b",
            "primary_background": "#12090b",
            "secondary_background": "#2a0f14",
            "panel": "#211417",
            "card": "#2d181c",
            "sidebar": "#0b0708",
            "accent": "#ef4444",
            "accent2": "#fb923c",
            "hover": "#3f2025",
            "active": "#b91c1c",
            "nav_active": "#b91c1c",
            "nav_hover": "#3f2025",
            "danger": "#f43f5e",
            "success": "#22c55e",
            "warning": "#f59e0b",
            "border": "#5a2f34",
            "shadow_color": "#ef4444",
            "text": "#fff5f5",
            "muted_text": "#c39a9a",
            "rounding": 7,
            "padding": 14,
            "item_spacing": 10,
            "frame_padding": 8,
            "window_padding": 14,
            "font_scale": 1.0,
            "border_thickness": 1,
            "button_height": 34,
            "card_padding": 14,
            "glow_intensity": 0.6,
            "alpha": 0.98,
            "shadow": "soft",
        },
        "Frosted Glass": {
            "background": "#172230",
            "primary_background": "#172230",
            "secondary_background": "#d8eefc",
            "panel": "#273849",
            "card": "#31465a",
            "sidebar": "#203040",
            "accent": "#7dd3fc",
            "accent2": "#c4b5fd",
            "hover": "#405a70",
            "active": "#256d8e",
            "nav_active": "#256d8e",
            "nav_hover": "#405a70",
            "danger": "#fb7185",
            "success": "#5eead4",
            "warning": "#fde68a",
            "border": "#84a5bb",
            "shadow_color": "#7dd3fc",
            "text": "#f8fbff",
            "muted_text": "#c0cfdb",
            "rounding": 14,
            "padding": 16,
            "item_spacing": 12,
            "frame_padding": 9,
            "window_padding": 16,
            "font_scale": 1.0,
            "border_thickness": 1,
            "button_height": 36,
            "card_padding": 18,
            "glow_intensity": 0.5,
            "alpha": 0.88,
            "shadow": "glass",
        },
        "Minimal Pro": {
            "background": "#111317",
            "primary_background": "#111317",
            "secondary_background": "#1b1f26",
            "panel": "#1d222b",
            "card": "#242a34",
            "sidebar": "#15191f",
            "accent": "#e5e7eb",
            "accent2": "#94a3b8",
            "hover": "#2a313c",
            "active": "#3a4351",
            "nav_active": "#3a4351",
            "nav_hover": "#2a313c",
            "danger": "#ef4444",
            "success": "#22c55e",
            "warning": "#f59e0b",
            "border": "#343b47",
            "shadow_color": "#000000",
            "text": "#f8fafc",
            "muted_text": "#94a3b8",
            "rounding": 6,
            "padding": 13,
            "item_spacing": 9,
            "frame_padding": 7,
            "window_padding": 13,
            "font_scale": 1.0,
            "border_thickness": 1,
            "button_height": 32,
            "card_padding": 14,
            "glow_intensity": 0.2,
            "alpha": 1.0,
            "shadow": "none",
        },
        "Midnight Gold": {
            "background": "#10121a",
            "primary_background": "#10121a",
            "secondary_background": "#211c12",
            "panel": "#1a1d28",
            "card": "#242332",
            "sidebar": "#0d1018",
            "accent": "#f2c94c",
            "accent2": "#f59e0b",
            "hover": "#352d1e",
            "active": "#9a6b12",
            "nav_active": "#9a6b12",
            "nav_hover": "#352d1e",
            "danger": "#ef4444",
            "success": "#22c55e",
            "warning": "#facc15",
            "border": "#4d432c",
            "shadow_color": "#f2c94c",
            "text": "#fff9e8",
            "muted_text": "#b8aa88",
            "rounding": 9,
            "padding": 14,
            "item_spacing": 10,
            "frame_padding": 8,
            "window_padding": 14,
            "font_scale": 1.0,
            "border_thickness": 1,
            "button_height": 35,
            "card_padding": 15,
            "glow_intensity": 0.55,
            "alpha": 0.98,
            "shadow": "soft",
        },
        "Toxic Green": {
            "background": "#0b1107",
            "primary_background": "#0b1107",
            "secondary_background": "#16240c",
            "panel": "#162010",
            "card": "#1f2d16",
            "sidebar": "#070d05",
            "accent": "#84cc16",
            "accent2": "#bef264",
            "hover": "#2d421b",
            "active": "#4d7c0f",
            "nav_active": "#4d7c0f",
            "nav_hover": "#2d421b",
            "danger": "#ef4444",
            "success": "#a3e635",
            "warning": "#facc15",
            "border": "#3f5f25",
            "shadow_color": "#84cc16",
            "text": "#f7ffe8",
            "muted_text": "#a8bd86",
            "rounding": 8,
            "padding": 14,
            "item_spacing": 10,
            "frame_padding": 8,
            "window_padding": 14,
            "font_scale": 1.0,
            "border_thickness": 1,
            "button_height": 34,
            "card_padding": 14,
            "glow_intensity": 0.7,
            "alpha": 0.98,
            "shadow": "glow",
        },
        "Ocean Glow": {
            "background": "#07151e",
            "primary_background": "#07151e",
            "secondary_background": "#0f2d3c",
            "panel": "#122634",
            "card": "#183445",
            "sidebar": "#0a1b25",
            "accent": "#22d3ee",
            "accent2": "#38bdf8",
            "hover": "#21485b",
            "active": "#0e7490",
            "nav_active": "#0e7490",
            "nav_hover": "#21485b",
            "danger": "#fb7185",
            "success": "#2dd4bf",
            "warning": "#fbbf24",
            "border": "#2f6277",
            "shadow_color": "#22d3ee",
            "text": "#effdff",
            "muted_text": "#98c6d2",
            "rounding": 10,
            "padding": 15,
            "item_spacing": 11,
            "frame_padding": 8,
            "window_padding": 15,
            "font_scale": 1.0,
            "border_thickness": 1,
            "button_height": 35,
            "card_padding": 16,
            "glow_intensity": 0.65,
            "alpha": 0.98,
            "shadow": "glow",
        },
        "Sunset Neon": {
            "background": "#1b1018",
            "primary_background": "#1b1018",
            "secondary_background": "#341b22",
            "panel": "#2a1a27",
            "card": "#3a2031",
            "sidebar": "#160c13",
            "accent": "#fb7185",
            "accent2": "#f97316",
            "hover": "#4a2737",
            "active": "#be3455",
            "nav_active": "#be3455",
            "nav_hover": "#4a2737",
            "danger": "#f43f5e",
            "success": "#34d399",
            "warning": "#fb923c",
            "border": "#6a3348",
            "shadow_color": "#fb7185",
            "text": "#fff7fa",
            "muted_text": "#d5a5b4",
            "rounding": 11,
            "padding": 15,
            "item_spacing": 11,
            "frame_padding": 8,
            "window_padding": 15,
            "font_scale": 1.0,
            "border_thickness": 1,
            "button_height": 35,
            "card_padding": 16,
            "glow_intensity": 0.7,
            "alpha": 0.98,
            "shadow": "glow",
        },
    }
)


PRESET_CATEGORIES = [
    "All",
    "Hero Sections",
    "Feature Cards",
    "Buttons",
    "Sliders",
    "Toggles",
    "Social Blocks",
    "Status Panels",
    "Login/Auth Blocks",
    "Config Blocks",
    "Animated Backgrounds",
    "Navigation Styles",
    "Info Panels",
    "Dashboard Cards",
]


ELEMENT_PRESETS = [
    {
        "name": "Hero CTA Block",
        "category": "Hero Sections",
        "description": "Large heading, supporting copy, and primary/secondary actions.",
        "tags": ["hero", "button", "cta"],
        "animation": {"enabled": True, "type": "Fade In", "duration": 0.6, "delay": 0.05, "speed": 1.0, "intensity": 0.8, "loop": False},
        "components": [
            {"type": "header_text", "label": "Build Better Tools", "width": 360, "height": 38, "auto_center": True},
            {"type": "text_label", "label": "Design polished ImGui interfaces visually, then export clean C++.", "width": 420, "height": 28, "auto_center": True},
            {"type": "button", "label": "Launch Builder", "width": 180, "height": 36, "auto_center": True},
            {"type": "button", "label": "View Examples", "width": 160, "height": 34, "auto_center": True, "color": "#2f3b52"},
        ],
    },
    {
        "name": "Launch Panel",
        "category": "Hero Sections",
        "description": "Feature-card launch panel with status and start action.",
        "tags": ["launcher", "hero", "card"],
        "animation": {"enabled": True, "type": "Slide In Up", "duration": 0.55, "speed": 1.0, "intensity": 0.9, "loop": False},
        "components": [
            {"type": "feature_card", "label": "Launch Workspace", "width": 360, "height": 104, "props": {"title": "Launch Workspace", "description": "Open the primary workspace with your saved local settings.", "button_text": "Launch"}},
            {"type": "status_badge", "label": "Ready", "width": 130, "props": {"status": "Ready", "badge_color": "#28c487"}},
        ],
    },
    {
        "name": "Welcome Action Card",
        "category": "Hero Sections",
        "description": "Compact welcome block for dashboards and launchers.",
        "tags": ["welcome", "card", "button"],
        "animation": {"enabled": True, "type": "Hover Glow", "duration": 0.35, "speed": 1.0, "intensity": 0.6, "loop": True},
        "components": [
            {"type": "header_text", "label": "Welcome Back", "width": 320, "height": 34},
            {"type": "text_label", "label": "Everything is ready for your next session.", "width": 340, "height": 26},
            {"type": "button", "label": "Continue", "width": 150, "height": 34},
        ],
    },
    {
        "name": "Premium Slider Row",
        "category": "Sliders",
        "description": "Label, description, slider, value readout, and reset action.",
        "tags": ["slider", "settings", "row"],
        "animation": {"enabled": True, "type": "Hover Glow", "duration": 0.25, "speed": 1.0, "intensity": 0.45, "loop": True},
        "components": [
            {"type": "text_label", "label": "Interface Scale", "width": 260, "height": 24},
            {"type": "text_label", "label": "Adjust the menu scale for your display.", "width": 330, "height": 24, "text_color": "#96a0b5"},
            {"type": "slider_float", "label": "Scale", "width": 310, "props": {"min": 0.75, "max": 1.5, "default_value": 1.0, "format": "%.2f"}},
            {"type": "button", "label": "Reset Scale", "width": 130, "height": 32, "color": "#2f3b52"},
        ],
    },
    {
        "name": "Settings Slider Card",
        "category": "Sliders",
        "description": "Card-style slider for numeric settings.",
        "tags": ["slider", "card"],
        "components": [
            {"type": "feature_card", "label": "Performance Budget", "width": 340, "height": 86, "props": {"title": "Performance Budget", "description": "Tune the amount of visual polish used by the interface.", "button_text": "Auto"}},
            {"type": "slider_int", "label": "Budget", "width": 320, "props": {"min": 0, "max": 100, "default_value": 70, "format": "%d%%"}},
        ],
    },
    {
        "name": "Glow Toggle Card",
        "category": "Toggles",
        "description": "Toggle card with a live enabled status badge.",
        "tags": ["toggle", "glow", "card"],
        "animation": {"enabled": True, "type": "Pulse Glow", "duration": 0.8, "speed": 2.0, "intensity": 0.7, "loop": True},
        "components": [
            {"type": "checkbox", "label": "Enable Ambient Glow", "width": 280, "props": {"default_value": True}},
            {"type": "text_label", "label": "Adds a soft animated accent around important panels.", "width": 360, "height": 24, "text_color": "#96a0b5"},
            {"type": "status_badge", "label": "Enabled", "width": 120, "props": {"status": "Enabled", "badge_color": "#28c487"}},
        ],
    },
    {
        "name": "Feature Toggle Row",
        "category": "Toggles",
        "description": "Simple feature row with toggle and status.",
        "tags": ["toggle", "settings"],
        "components": [
            {"type": "checkbox", "label": "Enable Notifications", "width": 280, "props": {"default_value": False}},
            {"type": "status_badge", "label": "Optional", "width": 112, "props": {"status": "Optional", "badge_color": "#f59e0b"}},
        ],
    },
    {
        "name": "Mode Selector",
        "category": "Info Panels",
        "description": "Combo selector with helper text and badge.",
        "tags": ["combo", "mode", "selector"],
        "components": [
            {"type": "text_label", "label": "Operation Mode", "width": 240},
            {"type": "combo_box", "label": "Mode", "width": 300, "props": {"options": ["Balanced", "Performance", "Quiet"], "default_index": 0}},
            {"type": "status_badge", "label": "Balanced", "width": 130, "props": {"status": "Balanced", "badge_color": "#4f8cff"}},
        ],
    },
    {
        "name": "Theme Dropdown Card",
        "category": "Info Panels",
        "description": "Theme selection card with small explanatory copy.",
        "tags": ["combo", "theme", "card"],
        "components": [
            {"type": "header_text", "label": "Theme"},
            {"type": "text_label", "label": "Choose a visual preset for this menu.", "width": 330, "text_color": "#96a0b5"},
            {"type": "combo_box", "label": "Theme Preset", "width": 300, "props": {"options": ["Cyber Blue", "Minimal Pro", "Frosted Glass", "Sunset Neon"], "default_index": 0}},
        ],
    },
    {
        "name": "Creator Social Footer",
        "category": "Social Blocks",
        "description": "Compact social footer with six platform buttons.",
        "tags": ["social", "footer", "links"],
        "components": [
            {"type": "footer_text", "label": "Follow the project", "width": 260},
            {"type": "social_link", "label": "Discord", "props": {"platform": "Discord", "url": "https://discord.com/", "icon": "[D]"}},
            {"type": "social_link", "label": "YouTube", "props": {"platform": "YouTube", "url": "https://youtube.com/", "icon": "[YT]"}},
            {"type": "social_link", "label": "TikTok", "props": {"platform": "TikTok", "url": "https://tiktok.com/", "icon": "[TT]"}},
            {"type": "social_link", "label": "GitHub", "props": {"platform": "GitHub", "url": "https://github.com/", "icon": "[GH]"}},
            {"type": "social_link", "label": "Website", "props": {"platform": "Website", "url": "https://example.com/", "icon": "[WEB]"}},
            {"type": "social_link", "label": "Twitter/X", "props": {"platform": "Twitter/X", "url": "https://x.com/", "icon": "[X]"}},
        ],
    },
    {
        "name": "Social Hub Block",
        "category": "Social Blocks",
        "description": "Header, description, and social actions.",
        "tags": ["social", "hub"],
        "components": [
            {"type": "header_text", "label": "Community"},
            {"type": "text_label", "label": "Stay connected across channels.", "width": 320, "text_color": "#96a0b5"},
            {"type": "social_link", "label": "Discord", "props": {"platform": "Discord", "url": "https://discord.com/", "icon": "[D]"}},
            {"type": "social_link", "label": "GitHub", "props": {"platform": "GitHub", "url": "https://github.com/", "icon": "[GH]"}},
            {"type": "social_link", "label": "Website", "props": {"platform": "Website", "url": "https://example.com/", "icon": "[WEB]"}},
        ],
    },
    {
        "name": "Premium Feature Card",
        "category": "Feature Cards",
        "description": "Polished feature tile with action button.",
        "tags": ["feature", "card"],
        "animation": {"enabled": True, "type": "Hover Scale", "duration": 0.2, "speed": 1.0, "intensity": 0.6, "loop": True},
        "components": [
            {"type": "feature_card", "label": "Workflow Automation", "width": 360, "height": 100, "props": {"title": "Workflow Automation", "description": "Bundle repeat actions into one clean launcher.", "icon": "[*]", "button_text": "Open", "locked": False}},
        ],
    },
    {
        "name": "Locked Feature Tile",
        "category": "Feature Cards",
        "description": "Locked card with badge and disabled action styling.",
        "tags": ["feature", "locked"],
        "components": [
            {"type": "feature_card", "label": "Advanced Reports", "width": 360, "height": 100, "enabled": False, "props": {"title": "Advanced Reports", "description": "Reserved for a later module or license tier.", "icon": "[LOCK]", "button_text": "Locked", "locked": True}},
            {"type": "status_badge", "label": "Locked", "width": 110, "props": {"status": "Locked", "badge_color": "#ef4444"}},
        ],
    },
    {
        "name": "Account Status Panel",
        "category": "Status Panels",
        "description": "Account name, status, license time, and progress bar.",
        "tags": ["account", "status", "license"],
        "components": [
            {"type": "header_text", "label": "Account"},
            {"type": "text_label", "label": "User: Local Designer", "width": 300},
            {"type": "status_badge", "label": "Active", "width": 120, "props": {"status": "Active", "badge_color": "#28c487"}},
            {"type": "text_label", "label": "License time remaining", "width": 260, "text_color": "#96a0b5"},
            {"type": "progress_bar", "label": "License", "width": 300, "props": {"value": 0.72, "overlay": "72%"}},
        ],
    },
    {
        "name": "License Info Card",
        "category": "Status Panels",
        "description": "Small license information block.",
        "tags": ["license", "status"],
        "components": [
            {"type": "feature_card", "label": "License", "width": 340, "height": 88, "props": {"title": "License", "description": "Local prototype license status and renewal timing.", "button_text": "Manage"}},
            {"type": "progress_bar", "label": "Days Remaining", "width": 300, "props": {"value": 0.45, "overlay": "14 days"}},
        ],
    },
    {
        "name": "Config Manager Panel",
        "category": "Config Blocks",
        "description": "Input, config list placeholder, and save/load/delete actions.",
        "tags": ["config", "save", "load"],
        "components": [
            {"type": "header_text", "label": "Config Manager"},
            {"type": "input_text", "label": "Config Name", "width": 300, "props": {"default_text": "default", "buffer_size": 128}},
            {"type": "combo_box", "label": "Saved Configs", "width": 300, "props": {"options": ["Default", "Work", "Presentation"], "default_index": 0}},
            {"type": "button", "label": "Save Config", "width": 140},
            {"type": "button", "label": "Load Config", "width": 140, "color": "#2f3b52"},
            {"type": "button", "label": "Delete Config", "width": 140, "color": "#ef4444"},
        ],
    },
    {
        "name": "Modern Login Block",
        "category": "Login/Auth Blocks",
        "description": "Username, password, key input, login, and register action.",
        "tags": ["login", "auth", "input"],
        "animation": {"enabled": True, "type": "Slide In Right", "duration": 0.5, "speed": 1.0, "intensity": 0.8, "loop": False},
        "components": [
            {"type": "header_text", "label": "Sign In"},
            {"type": "input_text", "label": "Username", "width": 310, "props": {"default_text": "", "buffer_size": 128}},
            {"type": "input_text", "label": "Password", "width": 310, "props": {"default_text": "", "buffer_size": 128}},
            {"type": "input_text", "label": "License Key", "width": 310, "props": {"default_text": "", "buffer_size": 192}},
            {"type": "button", "label": "Login", "width": 150},
            {"type": "button", "label": "Register", "width": 150, "color": "#2f3b52"},
        ],
    },
    {
        "name": "Cyber Grid Background",
        "category": "Animated Backgrounds",
        "description": "Applies a cyber grid animated background.",
        "tags": ["background", "grid", "animated"],
        "background": {"type": "Cyber Grid", "primary_color": "#07111f", "secondary_color": "#0c233d", "accent_color": "#28a8ff", "animation_speed": 1.2, "grid_size": 28, "glow_intensity": 0.7, "opacity": 1.0},
        "theme": "Cyber Blue",
        "components": [{"type": "footer_text", "label": "Background preset applied: Cyber Grid", "width": 320}],
    },
    {
        "name": "Floating Particles Background",
        "category": "Animated Backgrounds",
        "description": "Applies drifting particles over a dark panel background.",
        "tags": ["background", "particles", "animated"],
        "background": {"type": "Floating Particles", "primary_color": "#130b22", "secondary_color": "#251044", "accent_color": "#c084fc", "animation_speed": 0.9, "particle_count": 48, "glow_intensity": 0.65, "opacity": 0.92},
        "theme": "Neon Purple",
        "components": [{"type": "footer_text", "label": "Background preset applied: Floating Particles", "width": 360}],
    },
    {
        "name": "Gradient Glow Background",
        "category": "Animated Backgrounds",
        "description": "Applies a slow animated gradient glow.",
        "tags": ["background", "gradient", "glow"],
        "background": {"type": "Animated Gradient", "primary_color": "#07151e", "secondary_color": "#341b22", "accent_color": "#fb7185", "animation_speed": 0.65, "glow_intensity": 0.8, "opacity": 0.96},
        "theme": "Sunset Neon",
        "components": [{"type": "footer_text", "label": "Background preset applied: Animated Gradient", "width": 360}],
    },
    {
        "name": "Pill Navigation Starter",
        "category": "Navigation Styles",
        "description": "Applies top pill tabs and adds a small tab starter block.",
        "tags": ["navigation", "tabs"],
        "nav_position": "top",
        "nav_style": "pill tabs",
        "components": [
            {"type": "tab_button", "label": "Overview", "width": 130, "props": {"active": True}},
            {"type": "tab_button", "label": "Details", "width": 120},
            {"type": "tab_button", "label": "Settings", "width": 125},
        ],
    },
]


TEMPLATE_LIBRARY.update(
    {
        "Premium Software Launcher": {
            "project_name": "Premium Software Launcher",
            "menu_title": "Premium Launcher",
            "nav_position": "left",
            "nav_style": "vertical sidebar",
            "theme": "Cyber Blue",
            "background": {"type": "Animated Gradient", "primary_color": "#07111f", "secondary_color": "#0c233d", "accent_color": "#28a8ff", "animation_speed": 0.8, "glow_intensity": 0.75},
            "animation": {"enabled": True, "type": "Fade In", "duration": 0.6, "speed": 1.0, "intensity": 0.7, "loop": False},
            "categories": [
                {"name": "Home", "icon": "[H]", "presets": ["Hero CTA Block", "Account Status Panel", "Creator Social Footer"]},
                {"name": "Launch", "icon": "[*]", "presets": ["Launch Panel", "Premium Feature Card", "Locked Feature Tile"]},
                {"name": "Settings", "icon": "[S]", "presets": ["Premium Slider Row", "Glow Toggle Card", "Mode Selector"]},
            ],
        },
        "Cyber Settings Menu": {
            "project_name": "Cyber Settings Menu",
            "menu_title": "Cyber Settings",
            "nav_position": "left",
            "nav_style": "icon sidebar",
            "theme": "Cyber Blue",
            "background": {"type": "Cyber Grid", "primary_color": "#07111f", "secondary_color": "#0c233d", "accent_color": "#28a8ff", "animation_speed": 1.25, "grid_size": 26, "glow_intensity": 0.8},
            "categories": [
                {"name": "Controls", "icon": "[C]", "presets": ["Glow Toggle Card", "Feature Toggle Row", "Premium Slider Row"]},
                {"name": "Modes", "icon": "[M]", "presets": ["Mode Selector", "Theme Dropdown Card"]},
                {"name": "Status", "icon": "[S]", "presets": ["Account Status Panel"]},
            ],
        },
        "Creator/Social Hub": {
            "project_name": "Creator Social Hub",
            "menu_title": "Creator Hub",
            "nav_position": "top",
            "nav_style": "pill tabs",
            "theme": "Neon Purple",
            "background": {"type": "Floating Particles", "primary_color": "#130b22", "secondary_color": "#251044", "accent_color": "#c084fc", "animation_speed": 0.9, "particle_count": 54, "glow_intensity": 0.65},
            "categories": [
                {"name": "Profile", "icon": "[P]", "presets": ["Welcome Action Card", "Account Status Panel"]},
                {"name": "Social", "icon": "[WEB]", "presets": ["Social Hub Block", "Creator Social Footer"]},
                {"name": "Content", "icon": "[*]", "presets": ["Premium Feature Card", "Launch Panel"]},
            ],
        },
        "Config Manager UI": {
            "project_name": "Config Manager UI",
            "menu_title": "Config Manager",
            "nav_position": "left",
            "nav_style": "vertical sidebar",
            "theme": "Redline Dark",
            "background": {"type": "Scanlines", "primary_color": "#12090b", "secondary_color": "#2a0f14", "accent_color": "#ef4444", "animation_speed": 1.0, "opacity": 0.92},
            "categories": [
                {"name": "Configs", "icon": "[C]", "presets": ["Config Manager Panel"]},
                {"name": "Status", "icon": "[S]", "presets": ["License Info Card", "Feature Toggle Row"]},
                {"name": "Account", "icon": "[A]", "presets": ["Modern Login Block"]},
            ],
        },
        "Minimal Professional Menu": {
            "project_name": "Minimal Professional Menu",
            "menu_title": "Professional Menu",
            "nav_position": "top",
            "nav_style": "top tabs",
            "theme": "Minimal Pro",
            "background": {"type": "Linear Gradient Preview", "primary_color": "#111317", "secondary_color": "#1b1f26", "accent_color": "#94a3b8", "animation_speed": 0.35, "opacity": 1.0},
            "categories": [
                {"name": "Overview", "icon": "[H]", "presets": ["Welcome Action Card", "Mode Selector"]},
                {"name": "Settings", "icon": "[S]", "presets": ["Settings Slider Card", "Feature Toggle Row", "Theme Dropdown Card"]},
                {"name": "Info", "icon": "[I]", "presets": ["License Info Card", "Creator Social Footer"]},
            ],
        },
    }
)
